name: Build CIBA Example - ASP.NET

on:
  push:
    paths:
      - ".github/workflows/example-ciba-aspnet.yml"
      - "example-ciba-flow/aspnet-and-nextjs/backend/app/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: example-ciba-flow/aspnet-and-nextjs/backend/app
          file: example-ciba-flow/aspnet-and-nextjs/backend/app/Dockerfile
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
