name: Build Code Example - Spring

on:
  push:
    paths:
      - ".github/workflows/example-code-spring.yml"
      - "example-code-flow/spring-auth-only/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        working-directory: example-code-flow/spring-auth-only
        run: ./gradlew build --no-daemon
