name: Build Code Example - Next.js

on:
  push:
    paths:
      - ".github/workflows/example-code-nextjs.yml"
      - "example-code-flow/nextjs-fullstack/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('example-code-flow/nextjs-fullstack/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-            

      - name: Install pnpm dependencies
        working-directory: example-code-flow/nextjs-fullstack
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Run build
        working-directory: example-code-flow/nextjs-fullstack
        run: pnpm build
 